# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yKSWWgOVtKjji2hSeo5770FQUNbTV7r6
"""



"""

1.   Create a list named "fruits" containing three different fruits and display its items using for loop.

"""

n = 0
# Creating a list
fruits = ["Apple","Orange","Mango"]
print(type(fruits))
#Applying for loop
for i in range(3):
  n = n+1
  #Displaying all fruits
  print(n,fruits[i])

"""2. Create a tuple named "numbers" with five random numbers and display its item
using for loop.
"""

x = 0
#Creating a tuple
numbers = (51,565,65,35,5)

print(type(numbers))

#Applying for loop
for i in numbers:
  x = x+1
  #Displaying all numbers
  print(x,".",i)

"""3. Create a set named "colors" with three different colors and display its items using
for loop
"""

i = 0
#Creating a set of color
colors = {"Blue","White","Red"}

print(type(colors))

#Applying for loop
for x in colors:
  i = i+1
  print(i,".",x)

"""4. Create a dictionary named "student" with the following key-value pairs:

  i. "name" as the key and the student's name as the value.

  ii. "age" as the key and the student's age as the value.

  iii. "grade" as the key and the student's grade as the value.

  iv. Iterate over the dictionary using the for loop and display its keys.

  v. Iterate over the dictionary using the for loop and display its values.
"""

x = 0

#Creating a dictionary
student = {"name":"Waja DadKarim","age":"25","grade":"B"}

print(type(student))

#Applying for loop
for i in student:
  x = x+1
  print(x,".",i,":",student[i])

"""5. Create a multi-line string named "poem" with a short poem of your choice."""

#Creating a multi-line string
poem =  ''' Whispers of Twilight:
            In twilight’s hush, the stars ignite, A canvas painted with silver light.
            Moonbeams weave their gentle spell, As night unfolds its secrets well.

            The breeze, a soft and whispered song, Carries dreams where shadows throng.
            And in this quiet, mystical hour, Hope blooms anew, like a fragile flower. '''
print (type(poem))

"""6. Write an if statement to check if the length of the "fruits" list is greater than 3. If it
is, print "You have many fruits!".
"""

# Creating a list
fruits = ["Apple","Orange","Mango"]

#Calculating the list size
size = len(fruits)
print("The list size is ",size)

#Creating an if statement
if size > 3:
  print("You have many fruits")

#Applying an else statement
else:
  print("You have three fruits")

"""7. Create a program that takes a student's numerical grade as input and prints a corresponding letter grade. Use if-else statements to classify the grade into
categories such as "A," "B," "C," "D," or "F".

  i. If the numerical grade is 90 or higher, the corresponding letter grade is "A."
  
  ii. If the numerical grade is between 80 and 89 (inclusive), the corresponding letter grade is "B."
  
  iii. If the numerical grade is between 70 and 79 (inclusive), the corresponding letter grade is "C."
  
  iv. If the numerical grade is between 60 and 69 (inclusive), the corresponding letter grade is "D."
  
  v. If the numerical grade is below 60, the corresponding letter grade is "F."
"""

Student_Num = input("Enter your marks ")
if int(Student_Num) > 100:
  print("Please Recheck")
elif int(Student_Num) >= 90 and int(Student_Num) <= 100:
  print("Grade = A")
elif int(Student_Num) >= 80 and int(Student_Num) <= 89:
  print("Grade = B")
elif int(Student_Num) >= 70 and int(Student_Num) <= 79:
  print("Grade = C")
elif int(Student_Num) >= 60 and int(Student_Num) <= 69:
  print("Grade = D")
else:
  print("Grade = F")

"""8. Create a program that takes a temperature in Celsius as input from user and
classifies it into categories like "Freezing," "Cold," "Moderate," "Warm," or "Hot". Use if-else statements to define the temperature ranges for each category.

  i. If the temperature is below -10 degrees Celsius, it's classified as "Freezing."

  ii. If the temperature is between -10 and 0 degrees Celsius (exclusive), it's
classified as "Cold."

  iii. If the temperature is between 0 and 20 degrees Celsius (exclusive), it's
classified as "Moderate."

  iv. If the temperature is between 20 and 30 degrees Celsius (exclusive), it's
classified as "Warm."

  v. If the temperature is 30 degrees Celsius or above, it's classified as "Hot.
"""

Temp = input("Please Enter the temperature. ")
if int(Temp) <= -10:
  print("Freezing")
elif int(Temp) > -10 and int(Temp) < 0:
  print("Cold")
elif int(Temp) > 0 and int(Temp) < 20:
  print("Moderate")
elif int(Temp) > 20 and int(Temp) < 30:
  print("Warm")
elif int(Temp) >= 30:
  print("Hot")
else:
  print("The temperature is = ",Temp,"°C")